spring:
  application:
    name: social-coordination-platform
server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/localgroupdb # replace with Atlas URI in production

app:
  jwt:
    secret: replace_this_jwt_secret_for_dev_only
    expiration-ms: 3600000
