spring:
  application:
    name: social-coordination-platform
  mongodb:
    auto-index-creation: true
    uri: mongodb+srv://anveshsrivastava9_db_user:5heRlpNb68ZqhzRz@socialcoordinationplatf.3ycjbgb.mongodb.net/social_coordination?retryWrites=true&w=majority&appName=SocialCoordinationPlatform
server:
  port: 8080

app:
  jwt:
    secret: replace_this_jwt_secret_for_dev_only
    expiration-ms: 3600000
